/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef ENGINEERING_UNITS_UNIT_CONVERSION_HPP
#define ENGINEERING_UNITS_UNIT_CONVERSION_HPP

#include <cstdint>
#include <ratio>
#include <utility>
#include <type_traits>

#include <engineering_units/unit/traits.hpp>
#include <engineering_units/unit/mixed_unit.hpp>
#include <engineering_units/unit/multiply.hpp>
#include <engineering_units/unit/pow.hpp>
#include <engineering_units/unit/simplify.hpp>

#include <engineering_units/detail/doxygen.hpp>

namespace engunits
{

namespace detail
{

template<class ... Ts>
constexpr auto do_simplify( mixed_unit<Ts...> const & )
{
    return simplifies( conversion_factor_with_unit<>(),
                       conversion_factor_with_unit<Ts...>() );
}

template<class Lhs>
constexpr auto do_simplify( Lhs const & lhs )
{
    return simplifies( conversion_factor_with_unit<>(), lhs );
}

constexpr auto do_simplify( dimensionless )
{
    return conversion_factor_with_unit<>();
}

template<class Lhs, class Rhs>
constexpr auto conversion_factor_helper( Lhs const &,
                                         Rhs const & )
{
    return do_simplify( inverse(unit_traits<Lhs>::flat()) * 
                        unit_traits<Rhs>::flat() );
}

template<class Rhs>
constexpr auto conversion_factor_helper( dimensionless const &,
                                         Rhs const & )
{
    return do_simplify( unit_traits<Rhs>::flat() );
}


template<class Lhs>
constexpr auto conversion_factor_helper( Lhs const &,
                                         dimensionless const & )
{
    return do_simplify( unit_traits<Lhs>::flat() );
}
    
constexpr auto conversion_factor_helper( dimensionless const &,
                                         dimensionless const & )
{
    return conversion_factor_with_unit<>();
}

template<class T>
constexpr bool is_unit_or_dimensionless_v = 
    is_unit_v<T> || 
    std::is_same<T, dimensionless>::value;

}

/**
 * @ingroup metafunctions
 * @{
 */

/**
 * @brief Checks if there is a conversion from the unit @p From to the unit @p To
 * 
 * @pre @p From and @p To must be either units or @c dimensionless.
 * 
 * Expands to `std::true_type` if the units are convertible, `std::false_type` otherwise.
 * 
 * @note `is_convertible_t<U,U>` is always true.
 * @note `is_convertible_t<U,T> = is_convertible_t<U,T>`
 * 
 * @sa is_convertible_t
 * @sa is_convertible
 */
template<class From, class To>
using is_convertible_t = ENGUNITS_UNSPECIFIED( typename
    std::is_same<
        decltype( 
            detail::conversion_factor_helper( 
                std::declval<To const &>(),
                std::declval<From const &>() )
        ),
        detail::conversion_factor_with_unit<>
    >::type );

/**
 * @brief Variable helper for @c is_convertible_t
 * 
 * Like @c is_convertible_t, but as a boolean instead of `std::integral_constant`.
 * 
 * @sa is_convertible_t
 * @sa is_convertible
 */
template<class From, class To>
constexpr bool is_convertible_v = is_convertible_t<From, To>::value;

/**
 * @brief Function helper for @c is_convertible_t
 * @return `std::true_type` if @p From is convertible to @p To, `std::false_type` otherwise.
 * 
 * @sa is_convertible_t
 * @sa is_convertible_v
 */
template<class From, class To>
constexpr auto is_convertible(From const &, To const &)
{
    return is_convertible_t<From, To>{};
}

/**
 * @brief Returns the conversion factor between two units.
 * @pre To use this function, `is_convertible_v<From, To>` must be true.
 * 
 * @return The conversion factor as a `long double`.
 * @warning If the two units are not convertible this will fail with a `static_assert` 
 *   Use `is_convertible` to check the precondition.
 * 
 * Computes a conversion factor between to units, that is the ratio between
 * @p To and @p From. 
 * 
 * 
 */
template<class From, class To>
constexpr ENGUNITS_ENABLE_IF_T(
    detail::is_unit_or_dimensionless_v<From> && 
    detail::is_unit_or_dimensionless_v<To>,
    long double ) conversion_factor( const From & from,
                                      const To & to )
{
    static_assert( is_convertible_v<From, To>,
                   " Can not convert <from> to <to> ");

    return detail::conversion_factor_helper( to, from ).factor();
}

/** @} */

}


#endif //ENGINEERING_UNITS_UNIT_CONVERSION_HPP
