/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef ENGINEERING_UNITS_DETAIL_DOXYGEN_HPP
#define ENGINEERING_UNITS_DETAIL_DOXYGEN_HPP

/**
 * @defgroup metafunctions Metafunctions
 * @defgroup operators Operators and functions
 */

// Hide all the sfinae magic from doxygen.
#ifdef ENGUNITS_DOXYGEN

#define ENGUNITS_UNSPECIFIED(...) unspecified
#define ENGUNITS_ENABLE_IF(C)
#define ENGUNITS_ENABLE_IF_T(C, T)  T

#else

#define ENGUNITS_UNSPECIFIED(...) __VA_ARGS__

#define ENGUNITS_ENABLE_IF(C)   \
    std::enable_if_t<           \
        (C),                    \
        int                     \
    > = 0

#define ENGUNITS_ENABLE_IF_T(C, ...)\
    std::enable_if_t<               \
        (C),                        \
        __VA_ARGS__                 \
    >


#endif //ENGUNITS_DOXYGEN


#endif //ENGINEERING_UNITS_DETAIL_DOXYGEN_HPP

